import { redirect } from "next/navigation";
import Link from "next/link";
import { ArrowRight, BarChart3, Boxes, Check, ChevronRight, Menu, ScanBarcode, ShieldCheck, Store } from "lucide-react";
import { getSession } from "@/lib/auth/session";
import { StoreLogo } from "@/components/brand/StoreLogo";
import { publicEnv } from "@/lib/config/env";
import { getPlatformPlanPricing } from "@/lib/services/plan-pricing.service";
import type { SubscriptionPlan } from "@/lib/config/subscription-plans";

const FEATURES = [
  { icon: ScanBarcode, title: "A faster checkout", body: "Scan products, accept Cash, MoMo and card payments, and keep every sale moving." },
  { icon: Boxes, title: "Stock you can trust", body: "Know what is selling, what is running low, and what needs to be reordered before the shelf is empty." },
  { icon: BarChart3, title: "A clearer business", body: "Daily sales, product performance and staff activity in one calm, useful portal." },
];

const PLANS: Array<{ key: SubscriptionPlan; name: string; body: string; featured: boolean; features: string[] }> = [
  { key: "STARTER", name: "Starter", body: "For small shops getting organised", featured: false, features: ["1 shop portal", "Up to 2 staff accounts", "POS, products and inventory", "Daily sales reports"] },
  { key: "GROWTH", name: "Growth", body: "For growing supermarkets and teams", featured: true, features: ["1 shop portal", "Up to 4 staff accounts", "Cash, MoMo and card payments", "Purchase orders and advanced reports"] },
  { key: "ENTERPRISE", name: "Enterprise", body: "For larger retail operations", featured: false, features: ["Unlimited staff accounts", "Custom retail workflows", "Advanced permissions and reporting", "Priority onboarding and support"] },
];

const FAQS = [
  { question: "Who is MyPOS for?", answer: "MyPOS is built for shops and supermarkets that need one place to manage checkout, products, stock, staff and sales reporting." },
  { question: "How do I get started?", answer: "Create a shop portal, add your products and opening stock, then invite your team with the access they need." },
  { question: "Can I track different payment methods?", answer: "The point of sale supports cash, mobile money and card payment workflows. Available payment processing depends on the options configured for your account." },
  { question: "Can I control what each staff member can do?", answer: "Yes. MyPOS uses staff roles and permissions so access to areas such as products, sales and reports can be limited by responsibility." },
  { question: "How is pricing handled?", answer: "Plan options and current prices are shown on the plans page. A 14-day trial is offered as described in the plan information; review the terms before subscribing." },
  { question: "Where can I get help or learn how my information is used?", answer: "Contact your store administrator for account access. Read our Privacy Policy for information handling, or use the support contact provided by your store." },
];

export default async function HomePage() {
  const session = await getSession();
  if (session) redirect("/dashboard");
  const pricing = await getPlatformPlanPricing();
  const pricingByKey = new Map(pricing.map((plan) => [plan.key, plan]));

  return (
    <main className="min-h-dvh overflow-hidden bg-[#f5f7f2] text-[#17221d]">
      <header className="relative z-10 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8 lg:px-10">
        <Link href="/" className="flex items-center gap-2.5"><StoreLogo size="sm" /><span className="text-lg font-bold tracking-tight">{publicEnv.appName}</span></Link>
        <nav className="hidden items-center gap-8 text-sm font-medium text-[#64716a] md:flex"><a href="#features" className="hover:text-[#17221d]">Why MyPOS</a><Link href="/plans" className="hover:text-[#17221d]">Update plans</Link><a href="#pricing" className="hover:text-[#17221d]">Pricing</a><a href="#how-it-works" className="hover:text-[#17221d]">How it works</a><a href="#faq" className="hover:text-[#17221d]">FAQ</a></nav>
        <div className="flex items-center gap-2"><Link href="/login" className="hidden rounded-lg px-3 py-2 text-sm font-semibold text-[#31523f] hover:bg-white sm:inline-flex">Sign in</Link><Link href="/register" className="inline-flex h-10 items-center gap-2 rounded-lg bg-[#1c724d] px-4 text-sm font-semibold text-white shadow-sm hover:bg-[#155e3f]">Start free trial <ArrowRight className="size-4" /></Link><button type="button" aria-label="Open menu" className="rounded-lg p-2 text-[#31523f] md:hidden"><Menu className="size-5" /></button></div>
      </header>

      <section className="relative mx-auto max-w-7xl px-5 pb-16 pt-10 sm:px-8 sm:pt-16 lg:px-10 lg:pb-24 lg:pt-20">
        <div className="grid items-center gap-14 lg:grid-cols-[0.9fr_1.1fr] lg:gap-12">
          <div className="relative z-10 max-w-xl">
            <p className="mb-5 inline-flex items-center gap-2 rounded-full border border-[#b9d7c2] bg-white/70 px-3 py-1.5 text-xs font-bold uppercase tracking-[0.16em] text-[#1c724d]"><span className="size-2 rounded-full bg-[#e5ad35]" /> Built for Ghanaian retail</p>
            <h1 className="max-w-xl text-5xl font-semibold leading-[0.98] tracking-[-0.04em] text-[#17221d] sm:text-6xl lg:text-7xl">Run the shop. See the whole picture.</h1>
            <p className="mt-6 max-w-lg text-lg leading-8 text-[#64716a]">MyPOS gives shops and supermarkets one reliable place to sell, manage stock, understand the numbers and grow with confidence.</p>
            <div className="mt-8 flex flex-wrap items-center gap-3"><Link href="/register" className="inline-flex h-12 items-center gap-2 rounded-lg bg-[#1c724d] px-5 text-sm font-bold text-white shadow-[0_10px_24px_-12px_#1c724d] hover:bg-[#155e3f]">Start your 14-day trial <ArrowRight className="size-4" /></Link><Link href="/plans" className="inline-flex h-12 items-center gap-2 rounded-lg border border-[#c7d1c9] bg-white px-5 text-sm font-bold text-[#31523f] hover:bg-[#f0f4ef]">View plans <ChevronRight className="size-4" /></Link><Link href="/login" className="inline-flex h-12 items-center gap-2 rounded-lg border border-[#c7d1c9] bg-white px-5 text-sm font-bold text-[#31523f] hover:bg-[#f0f4ef]">Sign in to portal</Link></div>
            <div className="mt-8 flex flex-wrap gap-x-5 gap-y-2 text-sm text-[#64716a]"><span className="flex items-center gap-1.5"><Check className="size-4 text-[#1c724d]" /> No setup fee</span><span className="flex items-center gap-1.5"><Check className="size-4 text-[#1c724d]" /> Cash, MoMo and card</span><span className="flex items-center gap-1.5"><Check className="size-4 text-[#1c724d]" /> Your own portal</span></div>
          </div>

          <div className="relative lg:pl-8">
            <div aria-hidden className="absolute -inset-8 -z-10 bg-[linear-gradient(135deg,rgba(217,235,218,0.9),rgba(245,247,242,0)_60%)]" />
            <div className="relative overflow-hidden rounded-2xl border border-[#d5dfd7] bg-white shadow-[0_30px_70px_-35px_rgba(27,66,45,0.55)]">
              <div className="flex items-center justify-between border-b border-[#e5ebe6] px-5 py-4"><div className="flex items-center gap-2"><span className="flex size-8 items-center justify-center rounded-lg bg-[#e6f2e9] text-[#1c724d]"><Store className="size-4" /></span><span className="text-sm font-bold">Adom Supermarket</span></div><span className="rounded-full bg-[#e7f5ec] px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-[#1c724d]">Today</span></div>
              <div className="grid grid-cols-3 gap-3 bg-[#f8faf8] p-5"><div className="rounded-xl border border-[#e5ebe6] bg-white p-3"><p className="text-[10px] font-semibold uppercase tracking-wide text-[#8a968e]">Sales today</p><p className="mt-2 text-xl font-bold text-[#17221d]">GH&#8373; 8,420</p><p className="mt-1 text-[10px] font-semibold text-[#1c724d]">+12.8%</p></div><div className="rounded-xl border border-[#e5ebe6] bg-white p-3"><p className="text-[10px] font-semibold uppercase tracking-wide text-[#8a968e]">Transactions</p><p className="mt-2 text-xl font-bold text-[#17221d]">184</p><p className="mt-1 text-[10px] text-[#8a968e]">Across 3 tills</p></div><div className="rounded-xl border border-[#e5ebe6] bg-white p-3"><p className="text-[10px] font-semibold uppercase tracking-wide text-[#8a968e]">Low stock</p><p className="mt-2 text-xl font-bold text-[#17221d]">07</p><p className="mt-1 text-[10px] font-semibold text-[#bc7c13]">Needs attention</p></div></div>
              <div className="grid gap-5 px-5 pb-5 sm:grid-cols-[1.25fr_0.75fr]"><div className="rounded-xl border border-[#e5ebe6] p-4"><div className="flex items-center justify-between"><p className="text-xs font-bold text-[#31523f]">Sales overview</p><span className="text-[10px] text-[#8a968e]">Last 7 days</span></div><div className="mt-5 flex h-28 items-end gap-2"><span className="h-[38%] flex-1 rounded-t-md bg-[#cfe6d5]" /><span className="h-[53%] flex-1 rounded-t-md bg-[#acd6b8]" /><span className="h-[44%] flex-1 rounded-t-md bg-[#cfe6d5]" /><span className="h-[70%] flex-1 rounded-t-md bg-[#78bc91]" /><span className="h-[61%] flex-1 rounded-t-md bg-[#acd6b8]" /><span className="h-[82%] flex-1 rounded-t-md bg-[#1c724d]" /><span className="h-[92%] flex-1 rounded-t-md bg-[#e5ad35]" /></div></div><div className="rounded-xl border border-[#e5ebe6] p-4"><p className="text-xs font-bold text-[#31523f]">Top products</p><div className="mt-4 space-y-3"><div><div className="flex justify-between text-[10px] text-[#64716a]"><span>Milk 1L</span><span>42%</span></div><div className="mt-1 h-1.5 rounded-full bg-[#e8eee9]"><div className="h-full w-[42%] rounded-full bg-[#1c724d]" /></div></div><div><div className="flex justify-between text-[10px] text-[#64716a]"><span>Rice 5kg</span><span>31%</span></div><div className="mt-1 h-1.5 rounded-full bg-[#e8eee9]"><div className="h-full w-[31%] rounded-full bg-[#e5ad35]" /></div></div><div><div className="flex justify-between text-[10px] text-[#64716a]"><span>Bread</span><span>18%</span></div><div className="mt-1 h-1.5 rounded-full bg-[#e8eee9]"><div className="h-full w-[18%] rounded-full bg-[#78bc91]" /></div></div></div></div></div>
            </div>
          </div>
        </div>
      </section>

      <section id="features" className="border-y border-[#dfe7e0] bg-white"><div className="mx-auto grid max-w-7xl gap-0 px-5 sm:px-8 md:grid-cols-3 lg:px-10">{FEATURES.map((feature, index) => <div key={feature.title} className={`py-8 md:px-8 md:py-12 ${index > 0 ? "border-t border-[#e5ebe6] md:border-l md:border-t-0" : ""}`}><feature.icon className="size-6 text-[#1c724d]" /><h2 className="mt-5 text-xl font-bold tracking-tight text-[#17221d]">{feature.title}</h2><p className="mt-2 max-w-sm text-sm leading-6 text-[#64716a]">{feature.body}</p></div>)}</div></section>

      <section id="how-it-works" className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[0.7fr_1.3fr] lg:px-10 lg:py-28"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#bc7c13]">From first sale to full control</p><h2 className="mt-4 max-w-md text-4xl font-semibold leading-tight tracking-[-0.03em]">A better rhythm for everyday retail.</h2><p className="mt-5 max-w-md leading-7 text-[#64716a]">Start with a clean setup, bring your team in, and let the portal turn the daily rush into useful business signals.</p></div><div className="grid gap-4 sm:grid-cols-3"><div className="border-t-2 border-[#1c724d] pt-5"><span className="text-sm font-bold text-[#1c724d]">01</span><h3 className="mt-4 font-bold">Create your portal</h3><p className="mt-2 text-sm leading-6 text-[#64716a]">Register your shop and configure your company details in minutes.</p></div><div className="border-t-2 border-[#e5ad35] pt-5"><span className="text-sm font-bold text-[#bc7c13]">02</span><h3 className="mt-4 font-bold">Set up your team</h3><p className="mt-2 text-sm leading-6 text-[#64716a]">Add tills, staff, products and opening stock with clear roles.</p></div><div className="border-t-2 border-[#1c724d] pt-5"><span className="text-sm font-bold text-[#1c724d]">03</span><h3 className="mt-4 font-bold">Sell with confidence</h3><p className="mt-2 text-sm leading-6 text-[#64716a]">Run checkout and keep an eye on the numbers from one place.</p></div></div></section>

      <section id="faq" className="border-t border-[#dfe7e0] bg-white px-5 py-20 sm:px-8 lg:px-10 lg:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[0.7fr_1.3fr]"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#bc7c13]">A few useful answers</p><h2 className="mt-4 max-w-sm text-4xl font-semibold leading-tight text-[#17221d]">Frequently asked questions</h2><p className="mt-4 max-w-sm text-sm leading-6 text-[#64716a]">Need more detail? Review the <Link href="/terms" className="font-semibold text-[#1c724d] underline underline-offset-4">Terms and Conditions</Link> or <Link href="/privacy-policy" className="font-semibold text-[#1c724d] underline underline-offset-4">Privacy Policy</Link>.</p></div><div className="divide-y divide-[#dfe7e0] border-y border-[#dfe7e0]">{FAQS.map((faq) => <details key={faq.question} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-base font-semibold text-[#17221d] marker:hidden"><span>{faq.question}</span><ChevronRight className="size-4 shrink-0 text-[#1c724d] transition-transform group-open:rotate-90" /></summary><p className="mt-3 max-w-2xl pr-8 text-sm leading-6 text-[#64716a]">{faq.answer}</p></details>)}</div></div></section>

      <section id="pricing" className="bg-[#183b2b] px-5 py-20 text-white sm:px-8 lg:px-10 lg:py-24"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#e5ad35]">Simple monthly plans</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.03em]">Start small. Grow when ready.</h2></div><p className="max-w-sm text-sm leading-6 text-white/65">Every plan starts with a 14-day free trial. No setup fee, no long contract.</p></div><div className="mt-10 grid gap-4 lg:grid-cols-3">{PLANS.map((plan) => { const livePlan = pricingByKey.get(plan.key); return <div key={plan.name} className={`rounded-xl border p-6 ${plan.featured ? "border-[#e5ad35] bg-[#214b36]" : "border-white/15 bg-white/5"}`}><div className="flex items-start justify-between"><h3 className="text-lg font-bold">{plan.name}</h3>{plan.featured && <span className="rounded-full bg-[#e5ad35] px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-[#183b2b]">Popular</span>}</div><p className="mt-3 text-sm text-white/65">{plan.body}</p><p className="mt-8 text-3xl font-semibold">{livePlan?.monthlyPrice !== null && <span className="text-base text-white/60">GHS </span>}{livePlan?.monthlyPrice === null ? "Custom" : livePlan?.monthlyPrice}<span className="text-sm font-normal text-white/55">{livePlan?.monthlyPrice !== null && " / month"}</span></p><ul className="mt-6 space-y-2 border-t border-white/10 pt-5">{plan.features.map((feature) => <li key={feature} className="flex items-start gap-2 text-sm text-white/75"><Check className="mt-0.5 size-4 shrink-0 text-[#e5ad35]" />{feature}</li>)}</ul><Link href="/register" className="mt-8 inline-flex h-11 w-full items-center justify-center gap-2 rounded-lg bg-white text-sm font-bold text-[#183b2b] hover:bg-[#f3f7f3]">Choose {plan.name} <ChevronRight className="size-4" /></Link></div>; })}</div></div></section>

      <footer className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-8 text-sm text-[#64716a] sm:flex-row sm:items-center sm:justify-between sm:px-8 lg:px-10"><div className="flex items-center gap-2"><StoreLogo size="sm" /><span className="font-bold text-[#31523f]">{publicEnv.appName}</span></div><div className="flex flex-wrap items-center gap-5"><span className="flex items-center gap-1.5"><ShieldCheck className="size-4 text-[#1c724d]" /> Secure, store-isolated portals</span><Link href="#faq" className="hover:text-[#17221d]">FAQ</Link><Link href="/privacy-policy" className="hover:text-[#17221d]">Privacy Policy</Link><Link href="/terms" className="hover:text-[#17221d]">Terms and Conditions</Link><Link href="/login" className="font-semibold text-[#31523f] hover:underline">Sign in <ArrowRight className="inline size-3.5" /></Link></div></footer>
    </main>
  );
}
